export enum RecipeId {
  AdvancedOilProcessing = 'advanced-oil-processing',
  BasicOilProcessing = 'basic-oil-processing',
  CoalLiquefaction = 'coal-liquefaction',
  CopperCable = 'copper-cable',
  ElectronicCircuit = 'electronic-circuit',
  IronOre = 'iron-ore',
  KovarexEnrichmentProcess = 'kovarex-enrichment-process',
  MiningProductivity = 'mining-productivity',
  PlasticBar = 'plastic-bar',
  Satellite = 'satellite',
  SolidFuelFromLightOil = 'solid-fuel-from-light-oil',
  SteelChest = 'steel-chest',
  UraniumProcessing = 'uranium-processing',
}
