export enum RecipeId {
  AdvancedOilProcessing = 'advanced-oil-processing',
  BasicOilProcessing = 'basic-oil-processing',
  Coal = 'coal',
  CoalLiquefaction = 'coal-liquefaction',
  CopperCable = 'copper-cable',
  CrudeOil = 'crude-oil',
  ElectronicCircuit = 'electronic-circuit',
  FillWaterBarrel = 'fill-water-barrel',
  HeavyOilCracking = 'heavy-oil-cracking',
  IronOre = 'iron-ore',
  KovarexEnrichmentProcess = 'kovarex-enrichment-process',
  MiningProductivity = 'mining-productivity',
  NuclearFuelReprocessing = 'nuclear-fuel-reprocessing',
  PlasticBar = 'plastic-bar',
  Satellite = 'satellite',
  SolidFuelFromLightOil = 'solid-fuel-from-light-oil',
  SteelChest = 'steel-chest',
  TransportBelt = 'transport-belt',
  UraniumProcessing = 'uranium-processing',
  Water = 'water',
  WoodenChest = 'wooden-chest',
}
