export enum ItemId {
  CargoWagon = 'cargo-wagon',
  FastInserter = 'fast-inserter',
  FluidWagon = 'fluid-wagon',
  Inserter = 'inserter',
  InserterCapacityBonus = 'inserter-capacity-bonus',
  IronGearWheel = 'iron-gear-wheel',
  IronPlate = 'iron-plate',
  LongHandedInserter = 'long-handed-inserter',
  MiningProductivity = 'mining-productivity',
  Module = 'module',
  Pipe = 'pipe',
  Production = 'production',
  ProductivityLimitation = 'productivity-module',
  Pumpjack = 'pumpjack',
  ResearchSpeed = 'research-speed',
  RocketPart = 'rocket-part',
  RocketSilo = 'rocket-silo',
  StackInserter = 'stack-inserter',
  Steam = 'steam',
  Substation = 'substation',
  TransportBelt = 'transport-belt',
  Water = 'water',
}
