export enum ItemId {
  AssemblingMachine1 = 'assembling-machine-1',
  CargoWagon = 'cargo-wagon',
  ElectricMiningDrill = 'electric-mining-drill',
  FastInserter = 'fast-inserter',
  FluidWagon = 'fluid-wagon',
  Inserter = 'inserter',
  IronGearWheel = 'iron-gear-wheel',
  IronPlate = 'iron-plate',
  Lab = 'lab',
  LongHandedInserter = 'long-handed-inserter',
  Module = 'module',
  Pipe = 'pipe',
  ProductivityLimitation = 'productivity-module',
  Pumpjack = 'pumpjack',
  RocketPart = 'rocket-part',
  SpaceSciencePack = 'space-science-pack',
  SpeedModule3 = 'speed-module-3',
  StackInserter = 'stack-inserter',
  Steam = 'steam',
  Substation = 'substation',
  TransportBelt = 'transport-belt',
  Water = 'water',
}
