export const ItemId = {
  BulkInserter: 'bulk-inserter',
  EpicQuality: 'epic-quality',
  FastInserter: 'fast-inserter',
  Inserter: 'inserter',
  LegendaryQuality: 'legendary-quality',
  LongHandedInserter: 'long-handed-inserter',
  MineControlTower: 'mine-control-tower',
  MiningMachine: 'mining-machine',
  Module: 'module',
  Pipe: 'pipe',
  Pumpjack: 'pumpjack',
  QualityModuleTechnology: 'quality-module-technology',
  Somersloop: 'somersloop',
};
