export enum Id {
  HeaderSettings = 'header-settings',
  HeaderIcon = 'header-icon',
  SettingsDisplayRatePerSecond = 'settings-display-persecond',
  SettingsDisplayRatePerMinute = 'settings-display-perminute',
  SettingsDisplayRatePerHour = 'settings-display-perhour',
  SettingsPrecisionBeltDecimals = 'settings-precision-belt-decimals',
  SettingsPrecisionBeltValue = 'settings-precision-belt-value',
  SettingsPrecisionBeltFractions = 'settings-precision-belt-fractions',
  SettingsPrecisionItemDecimals = 'settings-precision-item-decimals',
  SettingsPrecisionItemValue = 'settings-precision-item-value',
  SettingsPrecisionItemFractions = 'settings-precision-item-fractions',
  SettingsPrecisionFactoryDecimals = 'settings-precision-factory-decimals',
  SettingsPrecisionFactoryValue = 'settings-precision-factory-value',
  SettingsPrecisionFactoryFractions = 'settings-precision-factory-fractions',
}
