export type CollectionKey =
  | 'categoryIds'
  | 'itemIds'
  | 'beaconIds'
  | 'beltIds'
  | 'cargoWagonIds'
  | 'fluidWagonIds'
  | 'fuelIds'
  | 'machineIds'
  | 'moduleIds'
  | 'pipeIds'
  | 'technologyIds'
  | 'inserterIds'
  | 'recipeIds'
  | 'locationIds';
