name: pr-title
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
